version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  pedidos:
    image: tessar0/pedidos-food:1.3
    environment:
      HOST_EUREKA: eurekaserver
      DB_HOST: mysql
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
    entrypoint: ["sh", "-c", "sleep 30 && java -jar /app.jar"]
    depends_on:
      - mysql
      - rabbitmq

  pagamentos:
    image: tessar0/pagamentos-food:1.3
    environment:
      HOST_EUREKA: eurekaserver
      DB_HOST: mysql
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
    entrypoint: ["sh", "-c", "sleep 45 && java -jar /app.jar"]
    depends_on:
      - mysql
      - rabbitmq

  avaliacao:
    image: tessar0/avaliacao-food:1.3
    environment:
      HOST_EUREKA: eurekaserver
      DB_HOST: mysql
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
    entrypoint: ["sh", "-c", "sleep 55 && java -jar /app.jar"]
    depends_on:
      - mysql
      - rabbitmq

  produtos:
    image: tessar0/produtos-food:1.0
    environment:
      HOST_EUREKA: eurekaserver
      DB_HOST: mysql
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
    entrypoint: ["sh", "-c", "sleep 60 && java -jar /app.jar"]
    depends_on:
      - mysql
      - rabbitmq

  gateway:
    image: tessar0/gateway-food:1.2
    ports:
      - "8082:8082"
    environment:
      HOST_EUREKA: eurekaserver
    entrypoint: ["sh", "-c", "sleep 65 && java -jar /app.jar"]
    depends_on:
      - eurekaserver

  eurekaserver:
    image: tessar0/eureka-food:1.0
    ports:
      - "8080:8080" 
